package com.enterprise.inventory.service;

import com.enterprise.inventory.entity.Product;
import com.enterprise.inventory.repository.ProductRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
@RequiredArgsConstructor
public class StockAlertService {

    private final ProductRepository productRepository;
    private final EmailService emailService;

    private LocalDateTime lastEmailSent = null;

    private final String ALERT_EMAIL = "ponkarthika40@gmail.com";

    @Scheduled(fixedRate = 60000)
    public void checkLowStock() {

        List<Product> lowStockProducts =
                productRepository.findLowStockProducts();

        if (!lowStockProducts.isEmpty()) {

            if (lastEmailSent != null &&
                    lastEmailSent.plusHours(6).isAfter(LocalDateTime.now())) {
                return;
            }

            StringBuilder body = new StringBuilder();

            body.append("INVENTORY MANAGEMENT SYSTEM\n");
            body.append("LOW STOCK ALERT\n\n");

            body.append("The following products are running low in stock:\n\n");

            body.append("-------------------------------------------------\n");

            for (Product p : lowStockProducts) {

                int recommended =
                        p.getReorderLevel() * 2 - p.getQuantity();

                body.append("Product Name : ")
                        .append(p.getName())
                        .append("\nCurrent Stock : ")
                        .append(p.getQuantity())
                        .append("\nReorder Level : ")
                        .append(p.getReorderLevel())
                        .append("\nRecommended Order : ")
                        .append(recommended)
                        .append("\n-------------------------------------------------\n");
            }

            body.append("\nPlease restock these products as soon as possible.\n\n");

            body.append("Generated by Inventory System\n");

            body.append("Time : ")
                    .append(LocalDateTime.now().format(
                            DateTimeFormatter.ofPattern("dd MMM yyyy HH:mm")));

            // EMAIL SENDING PART
            try {

                emailService.sendLowStockAlert(
                        ALERT_EMAIL,
                        "Inventory System - Low Stock Alert",
                        body.toString()
                );

                lastEmailSent = LocalDateTime.now();

                System.out.println("Low stock email sent successfully");

            } catch (Exception e) {

                System.out.println("Email sending failed: " + e.getMessage());

            }
        }
    }
}